# Generated by Django 3.0.3 on 2021-04-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
